; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{E990FABB-C9A7-4E80-A0EB-8F6BB6205B89}
AppName=Pong!
AppVersion=1.0
;AppVerName=Pong! 1.0
AppPublisher=f(x) software
DefaultDirName={pf}\Pong! v1.0
DefaultGroupName=Pong!
AllowNoIcons=yes
InfoAfterFile=C:\Users\Runaldis\Desktop\Pong v1.0\README.txt
OutputDir=C:\Users\Runaldis\Desktop
OutputBaseFilename=setup_pong_1.0
Compression=lzma
SolidCompression=yes

[Languages]
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\Runaldis\Desktop\Pong v1.0\Pong!.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Runaldis\Desktop\Pong v1.0\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\Pong!"; Filename: "{app}\Pong!.exe"
Name: "{group}\{cm:UninstallProgram,Pong!}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\Pong!"; Filename: "{app}\Pong!.exe"; Tasks: desktopicon

